### ISSUE TITLE
Request for Dataset

### ISSUE THREAD

**Issue by JinghangLi** [neuromorphic-paris/ETTCM#1]
Hi, thank you for your work.

I noticed that the Dataset **VL.zip** provide with download link and commands `wget --header 'Host: spik.xyz' --header 'Sec-GPC: 1' 'https://spik.xyz/nc/index.php/s/ER6GMim9qPQRxaF/download/VL.zip' --output-document 'VL.zip' ` is not reachable, can you update the dataset download links?  

Thanks!

**Comment by umgnunes** [comment]
Hi, thanks for your interest!

The link has been updated.
